# Generated by Django 4.1.3 on 2022-11-24 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsponsor',
            name='money',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='olingan pul miqdori'),
        ),
        migrations.AlterField(
            model_name='studentsponsor',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='users.sponsormodel', verbose_name='sponsor'),
        ),
    ]
