# Generated by Django 4.1.3 on 2022-11-24 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_studentsponsor_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsponsor',
            name='money',
            field=models.PositiveIntegerField(default=None, verbose_name='olingan pul miqdori'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentsponsor',
            name='sponsor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='users.sponsormodel', verbose_name='sponsor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentsponsor',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='users.studentmodel', verbose_name='student'),
            preserve_default=False,
        ),
    ]
