# Generated by Django 4.1.3 on 2022-11-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_studentsponsor_money_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinearGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_sp', models.PositiveIntegerField(default=0)),
                ('number_st', models.PositiveIntegerField(default=0)),
                ('day', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Kunlik Statistika',
                'verbose_name_plural': 'Kunlar Statistikasi',
            },
        ),
    ]
