# Generated by Django 4.1.3 on 2022-11-29 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_lineargraph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinearGraph',
        ),
    ]
